---
name: Suggest ideas and updates for the Docs website
about: Make a suggestions or report a problem on the docs.github.com website.
labels: engineering
inputs:
- type: description
  attributes:
    value: |
      HUBBERS BEWARE! Please confirm you're on the github/docs-internal repo and not the github/docs repo before proceeding, unless you want to make your work public to the entire internet. The github/docs repo is open source and public to the entire internet.

      For questions, ask in Discussions: https://github.com/github/docs/discussions
- type: checkboxes
  label: Code of Conduct
  attributes:
    label: 'I agree to follow the Code of Conduct: https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md'
    required: true
    multi-select: false
    free-text: false
    choices:
      - label: I agree
- type: dropdown
  label: Contributing
  attributes:
    choices:
      - description: 'I have read the Contributing guide: https://github.com/github/docs/blob/main/CONTRIBUTING.md'
        required: true
        multi-select: false
        free-text: false
        choices:
          - description: I agree
            value: I agree
- type: dropdown
  label: Similar issue
  attributes:
    choices:
      - description: 'There is not a similar issue that has been already opened: https://github.com/github/docs/issues'
        required: true
        multi-select: false
        free-text: false
        choices:
          - description: No similar issues
            value: No similar issues
- type: textarea
  attributes:
    label: suggestion
    description: What changes are you suggesting?
    required: true
    placeholder: Explain, in writing, with as much detail as possible, what changes you're suggesting and why. Provide supporting information using screenshots and URLs where possible, to help us understand your suggested changes.
- type: textarea
  attributes:
    label: additional info
    description: Additional information
    required: false
    placeholder: Any additional information, configuration, or data that might be necessary to reproduce the issue.
